pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                bat '"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python315\\python.exe" -m pip install -r app/requirements.txt'
            }
        }

        stage('Test Application') {
            steps {
                bat '"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python315\\python.exe" -c "print(\'CI pipeline executed successfully\')"'
            }
        }
    }
}
